### ISSUE TITLE
Confusing typo errors for beginners

### ISSUE THREAD

**Issue by Iamnotn3rd** [lwinmoepaing/html-css-beginner#1]
Hello Ko Lwin, Thanks for writing this awesome book.I found that confusing typo errors when I'm just reviewing my html and css. I just found confusing typo errors in topic that explains about 'pseudo classes'. Some lines of the initial button examples used to explain about `:active`, `:focus` pseudo classes are wrong.
![Screenshot from 2024-09-12 21-48-58](https://github.com/user-attachments/assets/4d99aac2-d6cb-475a-8969-6a635a653e4a)
In above image, `border-radius: 1px solid #dfdfdf;` should be applied to `border`. For new learners, that's may be confusing. Thanks for your book.

**Comment by lwinmoepaing** [comment]
Thanks for your feedback! 
I’ll review the section on pseudo-classes and fix the typo in the button examples. 

Appreciate your input!
